name: Deploy MultiK8s
on:
  push:
    branches:
      - master

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t bhassan310/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true bhassan310/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v3'
        with:
          #credentials_json: '${{ secrets.GKE_SA_KEY }}'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT_EMAIL }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: multi-338920

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: multi-cluster
          location: us-central1-c

      - name: Build
        run: |-
          docker build -t bhassan310/multi-client-k8s-gh:latest -t bhassan310/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t bhassan310/multi-server-k8s-gh:latest -t bhassan310/multi-server-k8s-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t bhassan310/multi-worker-k8s-gh:latest -t bhassan310/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push bhassan310/multi-client-k8s-gh:latest
          docker push bhassan310/multi-server-k8s-gh:latest
          docker push bhassan310/multi-worker-k8s-gh:latest

          docker push bhassan310/multi-client-k8s-gh:${{ env.SHA }}
          docker push bhassan310/multi-server-k8s-gh:${{ env.SHA }}
          docker push bhassan310/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=bhassan310/multi-server-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=bhassan310/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=bhassan310/multi-worker-k8s-gh:${{ env.SHA }}
